version: '3'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  api:
    build: ../apps/api
    command: node dist/index.js
    depends_on: [db, redis]
  web:
    build: ../apps/web
    depends_on: [api]
